# Generated by Django 6.0.3 on 2026-03-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JanGym', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='gymhours',
            options={'verbose_name': 'Gym Hours', 'verbose_name_plural': 'Gym Hours'},
        ),
    ]
