# Generated by Django 6.0.2 on 2026-02-25 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JanGym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='member',
            name='summary',
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('datetime', models.DateField(blank=True, null=True)),
                ('res_num', models.UUIDField(default=uuid.uuid4, help_text='Reservation Number', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('c', 'Confirmed'), ('n', 'No Confirmation')], default='n', help_text='Confirmation status', max_length=1)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='JanGym.trainer')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
