# Generated by Django 6.0.3 on 2026-03-29 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JanGym', '0002_alter_faq_options_alter_gymhours_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutinstance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutinstance',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_timeslots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gymhours',
            options={},
        ),
        migrations.AlterField(
            model_name='workoutinstance',
            name='res_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
