# Generated by Django 6.0.2 on 2026-02-25 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JanGym', '0002_remove_member_isbn_remove_member_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'ordering': ['datetime', 'res_num', 'member', 'trainer']},
        ),
        migrations.AddField(
            model_name='reservations',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='JanGym.member'),
        ),
    ]
