# Generated by Django 6.0.3 on 2026-03-29 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JanGym', '0003_alter_workoutinstance_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymhours',
            options={'verbose_name': 'Gym Hour', 'verbose_name_plural': 'Gym Hours'},
        ),
    ]
