# Generated by Django 6.0.2 on 2026-02-25 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JanGym', '0003_alter_reservations_options_reservations_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='emp_num',
            field=models.OneToOneField(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='JanGym.employee'),
        ),
        migrations.AlterField(
            model_name='member',
            name='trainer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='JanGym.trainer'),
        ),
    ]
