# Generated by Django 6.0.2 on 2026-02-25 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JanGym', '0004_trainer_emp_num_alter_member_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_trainer',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='reservations',
            name='workout',
            field=models.CharField(blank=True, choices=[('u', 'Upper-body weights'), ('l', 'Lower-body weights'), ('a', 'Aerobic'), ('t', 'Trainer Choice')], default='t', help_text='Workout type', max_length=1),
        ),
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.CharField(choices=[('c', 'Confirmed'), ('n', 'No Confirmation')], max_length=1),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='emp_num',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='JanGym.employee'),
        ),
    ]
