# Generated by Django 6.0.3 on 2026-03-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JanGym', '0004_alter_gymhours_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
    ]
