# Generated by Django 6.0.2 on 2026-02-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JanGym', '0005_employee_is_trainer_reservations_workout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
