# Generated by Django 6.0.2 on 2026-02-25 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JanGym', '0006_alter_trainer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='emp_num',
        ),
        migrations.AddField(
            model_name='trainer',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JanGym.employee'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
