# Generated by Django 6.0.2 on 2026-02-25 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JanGym', '0007_remove_trainer_emp_num_trainer_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='member', to='JanGym.trainer'),
        ),
    ]
