# Generated by Django 6.0.3 on 2026-03-26 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JanGym', '0008_alter_member_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GymHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='User ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, choices=[('trainer', 'Trainer'), ('member', 'Member'), ('employee', 'Employee'), ('admin', 'Admin')], max_length=100, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='member',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='trainer',
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='member',
            name='goal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='certifications',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JanGym.trainer')),
            ],
            options={
                'unique_together': {('trainer', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JanGym.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JanGym.user'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JanGym.user'),
        ),
        migrations.CreateModel(
            name='WorkoutInstance',
            fields=[
                ('res_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Workout ID', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JanGym.member')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JanGym.timeslot')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JanGym.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JanGym.exercise')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JanGym.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JanGym.member')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JanGym.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JanGym.workoutplan'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Reservations',
        ),
    ]
