# Generated by Django 6.0.3 on 2026-03-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JanGym', '0009_exercise_faq_gymhours_user_remove_trainer_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JanGym.member'),
        ),
    ]
